In [34]:
#importing libraries 
import pandas as pd
import numpy as np
import math 
import operator

In [35]:
#READING DATA 
data = pd.read_csv('/Users/atifsiddiqui/Documents/Spring_2021/EECS_738/Zoo/diabetes.csv')
data = data.dropna() 

In [36]:
#Analysing Data
data.head()
data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 60.0 KB


In [38]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [39]:
print(data.dtypes)

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object


In [40]:
#Function to find the Euclidean Distance 
#Input :- training dataset  , testing dataset , size of data
#output :- returns the Euclidean Distance between each dataset
def EuclideanDistance(trainData, testData, dataSize):
    EuclideanDist = 0
    for col in range (dataSize):
        EuclideanDist += pow((testData[col] - trainData[col]), 2)
    EucideanDist = np.sqrt(EuclideanDist)
    return (EuclideanDist)
        

In [41]:
#Function to find k 
#Input:- The square root of the number of record in training dataset 
#Output:- returns odd no. 
def functionToFindK(x):
    m_k = int(np.floor(x))
    if(m_k%2 == 0):
        return m_k -1
    else:
        return m_k 

In [42]:
#K- Nearest Neighbor 
def KNN(trainingDataSet, testDataSet):
    #list to store the distances
    Dist = {}  
    k = functionToFindK(math.sqrt(len(trainingDataSet)))
    TestDSCol = testDataSet.shape[1]
    
    for tempCol in range(len(trainingDataSet)):
        localDistance = EuclideanDistance(trainingDataSet.iloc[tempCol], testDataSet, TestDSCol)
        Dist[tempCol] = localDistance[1] #euclidean distance stored 
        
        
    listSortedDistance = sorted(Dist.items(), key=operator.itemgetter(1)) #sorting the distance list 
    listOfNeighbors = []
    for temp in range(k):
        listOfNeighbors.append(listSortedDistance[temp][0])
   
    print("The value of K-->", k," and the nearest neighbours are---> ", listOfNeighbors)

In [43]:
X_test = np.array(data.iloc[380:768])

In [44]:
X_test

array([[  1.   , 107.   ,  72.   , ...,   0.821,  24.   ,   0.   ],
       [  0.   , 105.   ,  68.   , ...,   0.236,  22.   ,   0.   ],
       [  1.   , 109.   ,  60.   , ...,   0.947,  21.   ,   0.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [45]:
X_train = np.array(data.iloc[0:379])

In [46]:
X_train

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  0.   ,  98.   ,  82.   , ...,   0.299,  22.   ,   0.   ],
       [  1.   ,  87.   ,  60.   , ...,   0.509,  22.   ,   0.   ],
       [  4.   , 156.   ,  75.   , ...,   0.238,  32.   ,   1.   ]])

In [47]:
size = X_test.shape[1]
EuclideanDistance(X_train, X_test, size)


array([1.090000e+02, 1.206400e+04, 1.205600e+04, 2.119000e+03,
       1.212450e+05, 4.970800e+02, 5.878397e+00, 1.356000e+03,
       4.000000e+00])

In [48]:
functionToFindK(len(X_test))

387

In [49]:
KNN(data, X_test)

The value of K--> 27  and the nearest neighbours are--->  [740, 177, 345, 57, 693, 24, 159, 663, 161, 763, 745, 88, 744, 723, 614, 648, 603, 539, 755, 191, 281, 328, 516, 638, 591, 369, 689]
